[package]
name = "epub-optimizer"
version = "0.0.0"
authors = ["Joshua Li <josh@jrl.ninja>"]
license = "ISC"

[dependencies]
pico-args = { version = "0.3", default-features = false }
fastrand = { version = "1.1", default-features = false }
walkdir = { version = "2.3", default-features = false }
zip = { version = "0.5", default-features = false, features = ["deflate"] }
