[package]
name = "epub-optimizer"
version = "0.0.0"
authors = ["Joshua Li <josh@jrl.ninja>"]
license = "ISC"

[dependencies]
clap = "2.32"
tempfile = "3.0.2"
walkdir = "2.1.4"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
